### ISSUE TITLE
25 Steps results in 96% or 4% brightness!

### ISSUE THREAD

**Issue by vbbalaji** [alex6o/node-red-contrib-dynamic-dimmer#11]
When I use 25 steps, the resultant brightness stops at 96% or 4% depending upon 1 or 0 as input.

`[{"id":"bcb0e7be.6026d8","type":"dynamic-dimmer","z":"f871eeaa.558fa","name":"TheaterDimmer","eventInterval":"400","steps":"25","minValue":0,"maxValue":"100","x":740,"y":740,"wires":[["5e3d35a8.f394cc","adf45974.269498"]]}]`

**Comment by alex6o** [comment]
hi @vbbalaji! Thanks for reporting the issue, I can reproduce the issue and I will add it to my backlog!
