### ISSUE TITLE
Is this a bug or is it me?

### ISSUE THREAD

**Issue by joeblack2k** [alex6o/node-red-contrib-dynamic-dimmer#34]
Hey! 

thank you for making this node!

i'm trying to get a fan to dim to 0 

i have my fan properties set to: {"percentage":"{{payload}}"}
that works when i use you sample buttons to inject 0 or 100%

but when i make a function with: msg.payload = 0; 

it only works when i use the button to first set it to 100 then it works 1x 

this is my flow for the fan in the bathroom:

`[
    {
        "id": "9ac1d73af9509270",
        "type": "tab",
        "label": "Badkamer",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "32c50907.2cde1e",
        "type": "stoptimer",
        "z": "9ac1d73af9509270",
        "duration": "5",
        "units": "Minute",
        "payloadtype": "num",
        "payloadval": "0",
        "name": "Wait 5 Minutes",
        "x": 840,
        "y": 120,
        "wires": [
            [
                "cdfbf50a.3eecc8"
            ],
            []
        ]
    },
    {
        "id": "cdfbf50a.3eecc8",
        "type": "api-current-state",
        "z": "9ac1d73af9509270",
        "name": "High Humidity?",
        "server": "51041573183f2685",
        "version": 3,
        "outputs": 2,
        "halt_if": "65",
        "halt_if_type": "num",
        "halt_if_compare": "gt",
        "entity_id": "sensor.tado_badkamer_humidity",
        "state_type": "str",
        "blockInputOverrides": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "entity"
            }
        ],
        "for": 0,
        "forType": "num",
        "forUnits": "minutes",
        "x": 320,
        "y": 220,
        "wires": [
            [
                "7e082343.a7f13c"
            ],
            [
                "187c858b7dbd7e72"
            ]
        ]
    },
    {
        "id": "c5c47556.bb3f8",
        "type": "api-call-service",
        "z": "9ac1d73af9509270",
        "name": "Turn off fan",
        "server": "51041573183f2685",
        "version": 5,
        "debugenabled": false,
        "domain": "fan",
        "service": "set_percentage",
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "fan.nrg_itho_3564_fan"
        ],
        "data": "{\"percentage\":\"{{payload}}\"}",
        "dataType": "json",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "output_location": "",
        "output_location_type": "none",
        "x": 830,
        "y": 460,
        "wires": [
            [
                "c982004.28e78"
            ]
        ]
    },
    {
        "id": "7e082343.a7f13c",
        "type": "stoptimer",
        "z": "9ac1d73af9509270",
        "duration": "1",
        "units": "Minute",
        "payloadtype": "num",
        "payloadval": "0",
        "name": "Wait 1 min",
        "x": 830,
        "y": 180,
        "wires": [
            [
                "cdfbf50a.3eecc8"
            ],
            []
        ]
    },
    {
        "id": "43927abd.48ee2c",
        "type": "server-state-changed",
        "z": "9ac1d73af9509270",
        "name": "High Humidity",
        "server": "51041573183f2685",
        "version": 4,
        "exposeToHomeAssistant": false,
        "haConfig": [
            {
                "property": "name",
                "value": ""
            },
            {
                "property": "icon",
                "value": ""
            }
        ],
        "entityidfilter": "sensor.tado_badkamer_humidity",
        "entityidfiltertype": "exact",
        "outputinitially": false,
        "state_type": "str",
        "haltifstate": "70",
        "halt_if_type": "num",
        "halt_if_compare": "gt",
        "outputs": 2,
        "output_only_on_state_change": true,
        "for": "0",
        "forType": "num",
        "forUnits": "minutes",
        "ignorePrevStateNull": false,
        "ignorePrevStateUnknown": false,
        "ignorePrevStateUnavailable": false,
        "ignoreCurrentStateUnknown": false,
        "ignoreCurrentStateUnavailable": false,
        "outputProperties": [
            {
                "property": "payload",
                "propertyType": "msg",
                "value": "",
                "valueType": "entityState"
            },
            {
                "property": "data",
                "propertyType": "msg",
                "value": "",
                "valueType": "eventData"
            },
            {
                "property": "topic",
                "propertyType": "msg",
                "value": "",
                "valueType": "triggerId"
            }
        ],
        "x": 130,
        "y": 100,
        "wires": [
            [
                "595cf5bf.3e5e34"
            ],
            []
        ]
    },
    {
        "id": "595cf5bf.3e5e34",
        "type": "api-call-service",
        "z": "9ac1d73af9509270",
        "name": "Turn on fan",
        "server": "51041573183f2685",
        "version": 5,
        "debugenabled": false,
        "domain": "fan",
        "service": "set_percentage",
        "areaId": [],
        "deviceId": [],
        "entityId": [
            "fan.nrg_itho_3564_fan"
        ],
        "data": "{\"percentage\":100}",
        "dataType": "json",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "output_location": "",
        "output_location_type": "none",
        "x": 350,
        "y": 100,
        "wires": [
            [
                "32c50907.2cde1e"
            ]
        ]
    },
    {
        "id": "07b49201e4ae59d4",
        "type": "inject",
        "z": "9ac1d73af9509270",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 100,
        "y": 260,
        "wires": [
            [
                "cdfbf50a.3eecc8"
            ]
        ]
    },
    {
        "id": "bd25fca4.82f73",
        "type": "dynamic-dimmer",
        "z": "9ac1d73af9509270",
        "name": "",
        "eventInterval": "2000",
        "steps": 10,
        "minValue": "20",
        "maxValue": 100,
        "x": 630,
        "y": 460,
        "wires": [
            [
                "c5c47556.bb3f8"
            ]
        ]
    },
    {
        "id": "c982004.28e78",
        "type": "debug",
        "z": "9ac1d73af9509270",
        "name": "output",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 830,
        "y": 400,
        "wires": []
    },
    {
        "id": "4f1e61c5.be096",
        "type": "inject",
        "z": "9ac1d73af9509270",
        "name": "simple dim 100%",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "1.0",
        "payloadType": "num",
        "x": 150,
        "y": 540,
        "wires": [
            [
                "bd25fca4.82f73"
            ]
        ]
    },
    {
        "id": "1b13342.fc3a9cc",
        "type": "inject",
        "z": "9ac1d73af9509270",
        "name": "simple dim 0%",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "0",
        "payloadType": "num",
        "x": 160,
        "y": 480,
        "wires": [
            [
                "bd25fca4.82f73"
            ]
        ]
    },
    {
        "id": "187c858b7dbd7e72",
        "type": "function",
        "z": "9ac1d73af9509270",
        "name": "Fan Off",
        "func": "msg.payload = 20;\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 460,
        "y": 340,
        "wires": [
            [
                "bd25fca4.82f73"
            ]
        ]
    },
    {
        "id": "51041573183f2685",
        "type": "server",
        "name": "Home Assistant",
        "version": 2,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": "30"
    }
]
`

is it me? or is something wrong?

**Comment by alex6o** [comment]
Hello @joeblack2k! Thank you for using the node :) 
Maybe this is a bit confusing but the range for the input is **[0,1]**! In case you want to dim the fan to 20% with the function node you just need to set `msg.payload = 0.2;`. Please let me know if this resolves the issue!

**Comment by joeblack2k** [comment]
Hmm no, i'm still at loss 

whenever i press the inject 100% button the fan dims to 100% great.. that is what we expect
if the flow then triggers because of the humidity it goes down to 20% 

but only 1 time 
if i manually set the fan to 100% (by motion trigger or something) then nothing happens

i need to press the inject 100% first for the dimmer to work

https://imgur.com/wZkDw9i

**Comment by alex6o** [comment]
Hm maybe I missed something in the sample picture but I don't see the part about "if i manually set the fan to 100% (by motion trigger or something)". Please take into account that the dimmer node is stateful and this means that whenever you are changing the fan speed you need to send the new values through the dimmer node otherwise the node is more or less "out of sync".

**Comment by joeblack2k** [comment]
Oké understand! so the dimmer has a memory, i will work with the dimmer up and down then! thanks!

**Comment by alex6o** [comment]
yes exactly 😃 have fun with the node and let me know if you need anything else!
