### ISSUE TITLE
Feature Request - Enable setting of current value to max

### ISSUE THREAD

**Issue by ankitag984** [alex6o/node-red-contrib-dynamic-dimmer#5]
I have started to use this node all over my workflows, it is a rather handy tool, instead of playing with loops in NR. It does need a function to similar to RESET, say SET, which can be used to set the current value of the node. Need this to keep the value updated, in-case light is manually turned on by someone, turn off is covered by RESET.

**Comment by alex6o** [comment]
Hi! I am happy to hear that this node is useful for you 🎉 I really like this feature request and I will add this to my backlog. Your proposal about introducing a new command sounds already quite interesting. So sending the command SET with the target 0.3 will immediately set the node to 0.3 without any dim operation.

**Comment by alex6o** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Introduce SET command](https://trello.com/c/w9BGOTeU/1-introduce-set-command)

**Comment by ankitag984** [comment]
Can’t believe you got it in already! Thank you Alex! Excited to try it out tomorrow :)

**Comment by alex6o** [comment]
You're welcome @ankitag984! I hope it is working as expected. If you want to support this project please rate the node on https://flows.nodered.org/node/node-red-contrib-dynamic-dimmer ;)
