### ISSUE TITLE
Feature Request - ability to pass through topic and other values

### ISSUE THREAD

**Issue by csmale** [alex6o/node-red-contrib-dynamic-dimmer#6]
The output message at the moment is very minimal. I am trying to maximise reuse of nodes by making things parameter-driven. At the moment the dynamic dimmer breaks the chain as the output message doesn't contain any kind of reference back to the source. Would it be possible to allow the topic on the output message to be a copy of the topic from the input, or in some way user-settable? Or allow some user-defined reference in the input payload to be copied to the output?

**Comment by alex6o** [comment]
Hi! Thank you very much for your feedback! I think your requests makes perfectly sense and I will add it to my backlog. I will have a look how the std nodes are handling these cases to align the solution with them.

**Comment by alex6o** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PassThrough input event](https://trello.com/c/YlyzBk8z/2-passthrough-input-event)
